[build]
  base = "web"
  command = "cd web && npm install && npm run build"
  publish = "web/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NEXT_FORCE_EDGE_IMAGES = "true"

